# -*- coding: utf-8 -*-
"""Panda_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KTa0WivadapYyG6AIbyjBcKVCe0OhBGk
"""

import pandas as pd

df = pd.read_csv("avocado.csv")

df # to see all the data

df.head() # to see the head of the data

df.tail() #ending of the data

df["AveragePrice"].head()

df.AveragePrice.head()

albany_df = df[df['region']== "Albany"]
albany_df.head()

albany_df.index

albany_df.set_index("Date")

albany_df.head()

albany_df = albany_df.set_index("Date")

albany_df.head()

#albany_df.set_index("Date", inplace = True)

albany_df['AveragePrice'].plot()